name: Backend Node.js CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'backend/**'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [23.x, 24.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install dependencies for backend
        run: npm ci

      - name: Run Mocha tests for backend
        run: npm test
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}